server:
    port: 9191

spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            routes:
                - id: USER-SERVICE
                  uri: lb://USER-SERVICE
                  predicates:
                    - Path=/users/**
                
                - id: MESSAGE-SERVICE
                  uri: lb://MESSAGE-SERVICE
                  predicates:
                    - Path=/messages/**
            globalcors:
                corsConfigurations:
                  '[/**]':
                    allowedOrigins: "http://localhost:3000"
                    allowedMethods: "*"
                    allowedHeaders: "*"

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost